// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'savings.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

SavingsClass _$SavingsClassFromJson(Map<String, dynamic> json) => SavingsClass(
      name: json['name'] as String?,
      price: (json['price'] as num?)?.toDouble(),
      quantity: (json['quantity'] as num?)?.toDouble(),
      image: json['image'] as String?,
      toggle: json['toggle'] as bool?,
      returnn: json['returnn'] as String?,
      history: (json['history'] as List<dynamic>?)
          ?.map((e) => Records.fromJson(e as Map<String, dynamic>))
          .toList(),
      nextwithdrawaldate: json['nextwithdrawaldate'] as String?,
      autoSave: json['autoSave'] as bool?,
      createdat: json['createdat'] as String?,
      deletedat: json['deletedat'] as String?,
      updatedat: json['updatedat'] as String?,
      id: json['id'] as String?,
      profitpayoutInterval: json['profitpayoutInterval'] as String?,
      isActive: json['isActive'] as bool?,
      isDeleted: json['isDeleted'] as bool?,
      savingsInterval: json['savingsInterval'] as List<dynamic>?,
      strictAutoSave: json['strictAutoSave'] as bool?,
      v: (json['v'] as num?)?.toDouble(),
      planid: json['planid'] as String?,
      vplan: (json['vplan'] as num?)?.toDouble(),
      balance: (json['balance'] as num?)?.toDouble(),
      principal: (json['principal'] as num?)?.toDouble(),
      durationInDays: json['durationInDays'] as String?,
      autoSavePlan: json['autoSavePlan'] as bool?,
      isActivePlan: json['isActivePlan'] as bool?,
      createdatPlan: json['createdatPlan'] as String?,
      amounttosave: (json['amounttosave'] as num?)?.toDouble(),
      isclosed: json['isclosed'] as bool?,
      openforwithdrawal: json['openforwithdrawal'] as bool?,
      asset: json['asset'] as String?,
      maturitydate: json['maturitydate'] as String?,
      thissavingsinterval: json['thissavingsinterval'] as String?,
      userid: json['userid'] as String?,
      colors: json['colors'] as List<dynamic>?,
      penalty: json['penalty'] as String?,
      description: json['description'] as String?,
      withdrawalInterval: json['withdrawalInterval'] as String?,
    );

Map<String, dynamic> _$SavingsClassToJson(SavingsClass instance) =>
    <String, dynamic>{
      'name': instance.name,
      'withdrawalInterval': instance.withdrawalInterval,
      'profitpayoutInterval': instance.profitpayoutInterval,
      'id': instance.id,
      'image': instance.image,
      'returnn': instance.returnn,
      'createdat': instance.createdat,
      'createdatPlan': instance.createdatPlan,
      'penalty': instance.penalty,
      'deletedat': instance.deletedat,
      'planid': instance.planid,
      'updatedat': instance.updatedat,
      'durationInDays': instance.durationInDays,
      'thissavingsinterval': instance.thissavingsinterval,
      'nextwithdrawaldate': instance.nextwithdrawaldate,
      'asset': instance.asset,
      'userid': instance.userid,
      'description': instance.description,
      'maturitydate': instance.maturitydate,
      'quantity': instance.quantity,
      'price': instance.price,
      'toggle': instance.toggle,
      'v': instance.v,
      'vplan': instance.vplan,
      'balance': instance.balance,
      'principal': instance.principal,
      'amounttosave': instance.amounttosave,
      'isActive': instance.isActive,
      'isDeleted': instance.isDeleted,
      'autoSave': instance.autoSave,
      'strictAutoSave': instance.strictAutoSave,
      'autoSavePlan': instance.autoSavePlan,
      'isActivePlan': instance.isActivePlan,
      'isclosed': instance.isclosed,
      'openforwithdrawal': instance.openforwithdrawal,
      'savingsInterval': instance.savingsInterval,
      'history': instance.history,
      'colors': instance.colors,
    };
